/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapoeiraRouteImport } from './routes/capoeira'
import { Route as JiuJitsuRouteImport } from './routes/jiu-jitsu'
import { Route as ProjetoClubeEscolaRouteImport } from './routes/projeto-clube-escola'
import { Route as ProjetoSocialRouteImport } from './routes/projeto-social'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapoeiraRoute = CapoeiraRouteImport.update({
  id: '/capoeira',
  path: '/capoeira',
  getParentRoute: () => rootRouteImport,
} as any)
const JiuJitsuRoute = JiuJitsuRouteImport.update({
  id: '/jiu-jitsu',
  path: '/jiu-jitsu',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoClubeEscolaRoute = ProjetoClubeEscolaRouteImport.update({
  id: '/projeto-clube-escola',
  path: '/projeto-clube-escola',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoSocialRoute = ProjetoSocialRouteImport.update({
  id: '/projeto-social',
  path: '/projeto-social',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capoeira': typeof CapoeiraRoute
  '/jiu-jitsu': typeof JiuJitsuRoute
  '/projeto-clube-escola': typeof ProjetoClubeEscolaRoute
  '/projeto-social': typeof ProjetoSocialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capoeira': typeof CapoeiraRoute
  '/jiu-jitsu': typeof JiuJitsuRoute
  '/projeto-clube-escola': typeof ProjetoClubeEscolaRoute
  '/projeto-social': typeof ProjetoSocialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capoeira': typeof CapoeiraRoute
  '/jiu-jitsu': typeof JiuJitsuRoute
  '/projeto-clube-escola': typeof ProjetoClubeEscolaRoute
  '/projeto-social': typeof ProjetoSocialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capoeira'
    | '/jiu-jitsu'
    | '/projeto-clube-escola'
    | '/projeto-social'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capoeira'
    | '/jiu-jitsu'
    | '/projeto-clube-escola'
    | '/projeto-social'
  id:
    | '__root__'
    | '/'
    | '/capoeira'
    | '/jiu-jitsu'
    | '/projeto-clube-escola'
    | '/projeto-social'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapoeiraRoute: typeof CapoeiraRoute
  JiuJitsuRoute: typeof JiuJitsuRoute
  ProjetoClubeEscolaRoute: typeof ProjetoClubeEscolaRoute
  ProjetoSocialRoute: typeof ProjetoSocialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capoeira': {
      id: '/capoeira'
      path: '/capoeira'
      fullPath: '/capoeira'
      preLoaderRoute: typeof CapoeiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jiu-jitsu': {
      id: '/jiu-jitsu'
      path: '/jiu-jitsu'
      fullPath: '/jiu-jitsu'
      preLoaderRoute: typeof JiuJitsuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto-clube-escola': {
      id: '/projeto-clube-escola'
      path: '/projeto-clube-escola'
      fullPath: '/projeto-clube-escola'
      preLoaderRoute: typeof ProjetoClubeEscolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto-social': {
      id: '/projeto-social'
      path: '/projeto-social'
      fullPath: '/projeto-social'
      preLoaderRoute: typeof ProjetoSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapoeiraRoute: CapoeiraRoute,
  JiuJitsuRoute: JiuJitsuRoute,
  ProjetoClubeEscolaRoute: ProjetoClubeEscolaRoute,
  ProjetoSocialRoute: ProjetoSocialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
