/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CapoeiraRouteImport } from './routes/capoeira'
import { Route as JiuJitsuRouteImport } from './routes/jiu-jitsu'
import { Route as ProjetoClubeEscolaRouteImport } from './routes/projeto-clube-escola'
import { Route as ProjetoSocialRouteImport } from './routes/projeto-social'
import { Route as AdminIndexRouteImport } from './routes/admin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CapoeiraRoute = CapoeiraRouteImport.update({
  id: '/capoeira',
  path: '/capoeira',
  getParentRoute: () => rootRouteImport,
} as any)
const JiuJitsuRoute = JiuJitsuRouteImport.update({
  id: '/jiu-jitsu',
  path: '/jiu-jitsu',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoClubeEscolaRoute = ProjetoClubeEscolaRouteImport.update({
  id: '/projeto-clube-escola',
  path: '/projeto-clube-escola',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoSocialRoute = ProjetoSocialRouteImport.update({
  id: '/projeto-social',
  path: '/projeto-social',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/capoeira': typeof CapoeiraRoute
  '/jiu-jitsu': typeof JiuJitsuRoute
  '/projeto-clube-escola': typeof ProjetoClubeEscolaRoute
  '/projeto-social': typeof ProjetoSocialRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/capoeira': typeof CapoeiraRoute
  '/jiu-jitsu': typeof JiuJitsuRoute
  '/projeto-clube-escola': typeof ProjetoClubeEscolaRoute
  '/projeto-social': typeof ProjetoSocialRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/capoeira': typeof CapoeiraRoute
  '/jiu-jitsu': typeof JiuJitsuRoute
  '/projeto-clube-escola': typeof ProjetoClubeEscolaRoute
  '/projeto-social': typeof ProjetoSocialRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/capoeira'
    | '/jiu-jitsu'
    | '/projeto-clube-escola'
    | '/projeto-social'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/capoeira'
    | '/jiu-jitsu'
    | '/projeto-clube-escola'
    | '/projeto-social'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cadastro'
    | '/capoeira'
    | '/jiu-jitsu'
    | '/projeto-clube-escola'
    | '/projeto-social'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CadastroRoute: typeof CadastroRoute
  CapoeiraRoute: typeof CapoeiraRoute
  JiuJitsuRoute: typeof JiuJitsuRoute
  ProjetoClubeEscolaRoute: typeof ProjetoClubeEscolaRoute
  ProjetoSocialRoute: typeof ProjetoSocialRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capoeira': {
      id: '/capoeira'
      path: '/capoeira'
      fullPath: '/capoeira'
      preLoaderRoute: typeof CapoeiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jiu-jitsu': {
      id: '/jiu-jitsu'
      path: '/jiu-jitsu'
      fullPath: '/jiu-jitsu'
      preLoaderRoute: typeof JiuJitsuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto-clube-escola': {
      id: '/projeto-clube-escola'
      path: '/projeto-clube-escola'
      fullPath: '/projeto-clube-escola'
      preLoaderRoute: typeof ProjetoClubeEscolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto-social': {
      id: '/projeto-social'
      path: '/projeto-social'
      fullPath: '/projeto-social'
      preLoaderRoute: typeof ProjetoSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CadastroRoute: CadastroRoute,
  CapoeiraRoute: CapoeiraRoute,
  JiuJitsuRoute: JiuJitsuRoute,
  ProjetoClubeEscolaRoute: ProjetoClubeEscolaRoute,
  ProjetoSocialRoute: ProjetoSocialRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
